services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: truf-ms-app
    ports:
      - "8000:8080"
    env_file:
      - .env.docker
    volumes:
      - sqlite_data:/var/www/html/database
    restart: unless-stopped

volumes:
  sqlite_data:
